# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SGYdh0IEyYiVtYZpuu4dBsOam2C4K49f
"""

import numpy as np
from PIL import Image

def main() -> None:
    try:
        image = np.array(Image.open('cars.png').convert('RGB'))
    except FileNotFoundError:
        print("Ошибка: Файл cars.png не найден.")
        return

    rows, cols, _ = image.shape

    # Настройки
    BRIGHTNESS_THRESHOLD = 130

    # Насколько зеленый должен быть сильнее красного/синего
    COLOR_DIFFERENCE = 40

    # Минимальный размер объекта в пикселях
    MIN_PIXEL_COUNT = 30

    R = image[:, :, 0].astype(int)
    G = image[:, :, 1].astype(int)
    B = image[:, :, 2].astype(int)

    # Фильтр
    green_mask = (G > BRIGHTNESS_THRESHOLD) & \
                 (G > R + COLOR_DIFFERENCE) & \
                 (G > B + COLOR_DIFFERENCE)

    # Сохраняем маску
    Image.fromarray((green_mask * 255).astype(np.uint8)).save('debug_strict.png')
    print("Сохранен файл debug_strict.png")

    # Поиск объектов
    visited = np.zeros_like(green_mask, dtype=bool)
    final_count = 0

    # Список для хранения размеров найденных объектов
    found_sizes = []

    neighbors = [(-1, -1), (-1, 0), (-1, 1), (0, -1), (0, 1), (1, -1), (1, 0), (1, 1)]

    for y in range(rows):
        for x in range(cols):
            if green_mask[y, x] and not visited[y, x]:
                stack = [(y, x)]
                visited[y, x] = True
                pixel_count = 0

                while stack:
                    cy, cx = stack.pop()
                    pixel_count += 1

                    for dy, dx in neighbors:
                        ny, nx = cy + dy, cx + dx
                        if 0 <= ny < rows and 0 <= nx < cols:
                            if green_mask[ny, nx] and not visited[ny, nx]:
                                visited[ny, nx] = True
                                stack.append((ny, nx))

                # Сохраняем размер каждого найденного зеленого пятна
                if pixel_count > 5:
                    found_sizes.append(pixel_count)

                # Проверка на размер
                if pixel_count > MIN_PIXEL_COUNT:
                    final_count += 1

    print(f"--- РЕЗУЛЬТАТ ---")
    print(f"Всего найдено зеленых пятен (до фильтрации по размеру): {len(found_sizes)}")
    print(f"Размеры пятен: {found_sizes}")
    print(f"Итого свободных мест (пятен больше {MIN_PIXEL_COUNT} пикселей): {final_count}")

if __name__ == "__main__":
    main()

from google.colab import drive
drive.mount('/content/drive')